name: Tests

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Env variables
      run: |
        touch ./system/.env.test
        echo FEED_TAGS=${{ secrets.FEED_TAGS }} >> ./system/.env.test
        cat ./system/.env.test
    - name: Unit Tests
      run: |
        mamba --tags='unit'
    - name: Integration Tests
      run: |
        mamba --tags='integration'
    - name: Acceptance Tests
      run: |
        mamba --tags='acceptance'