name: Tests

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Env variables
      run: |
        touch ./system/.env.test
        echo BLOG_TABLE_URL=${{ secrets.BLOG_TABLE_URL }} >> ./system/.env.test
        echo BLOG_URL=${{ secrets.BLOG_URL }} >> ./system/.env.test
        echo BOT_CHATID=${{ secrets.BOT_CHATID }} >> ./system/.env.test
        echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> ./system/.env.test
        echo FEED_TAGS=${{ secrets.FEED_TAGS }} >> ./system/.env.test
        echo LAST_ENTRY_BOARD_MESSAGE_FILE_PATH=${{ secrets.LAST_ENTRY_BOARD_MESSAGE_FILE_PATH }} >> ./system/.env.test
        echo LAST_ENTRY_FILE_PATH=${{ secrets.LAST_ENTRY_FILE_PATH }} >> ./system/.env.test
        echo TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }} >> ./system/.env.test
        echo TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} >> ./system/.env.test
        echo TWITTER_ACCOUNT=${{ secrets.TWITTER_ACCOUNT }} >> ./system/.env.test
        echo TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} >> ./system/.env.test
        echo TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }} >> ./system/.env.test
    - name: Unit Tests
      run: |
        mamba --tags='unit'
    - name: Integration Tests
      run: |
        mamba --tags='integration'
    - name: Acceptance Tests
      run: |
        mamba --tags='acceptance'